### PR TITLE
Add Comment System

### PR DESCRIPTION
**Pull request by Aisuruneko**
work in progress 🥉

### CODE REVIEW

**Comment by Aisuruneko** [comment]
do you remember, the 21st night of september?

**Comment by Aisuruneko** [comment]
🥉

**Review by papertek — CHANGES_REQUESTED** [review]
buttons need `<button>` tag

**Review by papertek — APPROVED** [review]
seeem ok. need to add functions for the buttons in the textbox in another pr. also need some fixes for handling old data (old wiki)

**Comment by Aisuruneko** [comment]
🥉

**Pull request merged**
